# Generated by Django 3.1 on 2021-04-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_enroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='student_id',
            new_name='student',
        ),
    ]
