# Generated by Django 3.1.7 on 2021-04-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professors',
            new_name='Professor',
        ),
    ]
