# Generated by Django 3.1.7 on 2021-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_auto_20210415_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=200, null=True)),
                ('class_description', models.CharField(max_length=200, null=True)),
                ('unique_code', models.CharField(max_length=200, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
