# Generated by Django 3.1.7 on 2021-04-15 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0007_auto_20210415_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='unique_code',
            field=models.CharField(default=uuid.uuid4, max_length=8, null=True, unique=True),
        ),
    ]
