# Generated by Django 3.1 on 2021-04-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0009_auto_20210416_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='unique_code',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
